version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: local.Dockerfile
    command:
      - --default-authentication-plugin=mysql_native_password
    env_file:
      - ./docker/db.env
    ports:
      - "3306:3306"