FROM node:16-alpine AS base
WORKDIR /app

COPY package.json .

RUN npm install

FROM base AS build

ARG PORT
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG SMTP_TO_EMAIL
ARG SMTP_PASSWORD
ARG TOKEN_SECRET

ENV PORT=$PORT
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV SMTP_TO_EMAIL=$SMTP_TO_EMAIL
ENV SMTP_PASSWORD=$SMTP_PASSWORD
ENV TOKEN_SECRET=$TOKEN_SECRET

COPY --from=base /app/node_modules ./node_modules
COPY . .

RUN npm run build

FROM build AS RUN
CMD ["npm", "start"]

