name: Check and Build Project
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
    avoid_redundancy:
      runs-on: ubuntu-20.04
      steps:
        - name: Cancel Previous Redundant Builds
          uses: styfle/cancel-workflow-action@0.11.0
          with:
            access_token: ${{ github.token }}
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16.16.0
          uses: actions/setup-node@v3
          with:
            node-version: 16.16.0
            cache: 'npm'
        - run: npm ci
        - run: npm run test -- --coverage
        - name: Coverage report
          uses: eleboys/test-coverage-report-action@v1.0.2
          id: report
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            path: coverage/coverage-final.json
            title: Test Coverage
        - name: Print the output summary
          run: echo "Report coverage json ${{ steps.report.outputs.summary }}"
    build:
      needs: [ test ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16.16.0
          uses: actions/setup-node@v3
          with:
            node-version: 16.16.0
            cache: 'npm'
        - run: npm ci
        - run: npm run build
