name: Check and Build Project
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
    avoid_redundancy:
      runs-on: ubuntu-20.04
      steps:
        - name: Cancel Previous Redundant Builds
          uses: styfle/cancel-workflow-action@0.11.0
          with:
            access_token: ${{ github.token }}
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16.16.0
          uses: actions/setup-node@v3
          with:
            node-version: 16.16.0
            cache: 'npm'
        - run: npm ci
        - run: npm run test:coverage
        - name: Print the Total Coverage
          id: coverage-percent
          shell: bash
          run: |
            value=`sed -n 47p coverage/lcov-report/index.html | awk -F '>' '{print $2}' | awk -F '%' '{print $1}'`
            echo "::set-output name=coverage::$value"
            echo $value
        - name: Add Coverage Label
          uses: actions/github-script@v2
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              github.issues.setLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['COV: ${{steps.coverage-percent.outputs.coverage}}']
              })
    build:
      needs: [ test ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16.16.0
          uses: actions/setup-node@v3
          with:
            node-version: 16.16.0
            cache: 'npm'
        - run: npm ci
        - run: npm run build
