name: Check and Build Project
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
    avoid_reduncy:
      runs-on: ubuntu-20.04
      steps:
        - name: Cancel Previous Redundant Builds
          uses: styfle/cancel-workflow-action@0.11.0
          with:
            access_token: ${{ github.token }}
    pre-build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16.16.0
          uses: actions/setup-node@v3
          with:
            node-version: 16.16.0
            cache: 'npm'
        - run: npm ci
        - uses: actions/upload-artifact@v3.1.1
          with:
            name: pre-build
            path: pre-build
    test:
      needs: [ pre-build ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v3.0.1
          with:
            name: pre-build
            path: pre-build
        - name: Use Node.js 16.16.0
          uses: actions/setup-node@v3
          with:
            node-version: 16.16.0
            cache: 'npm'
        - run: npm run test
    build:
      needs: [ test ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/upload-artifact@v3.1.1
          with:
            name: pre-build
            path: pre-build
        - name: Use Node.js 16.16.0
          uses: actions/setup-node@v3
          with:
            node-version: 16.16.0
            cache: 'npm'
        - run: npm ci
        - run: npm run build
