name: Check and Build Project
on:
  pull_request:
    branches:
      - master
      - dev
env:
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
jobs:
    avoid_redundancy:
      runs-on: ubuntu-latest
      steps:
        - name: Cancel Previous Redundant Builds
          uses: styfle/cancel-workflow-action@0.12.1
          with:
            access_token: ${{ github.token }}
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.1.1
        - name: Use Node.js lts
          uses: actions/setup-node@v3
          with:
            node-version: 'lts/*'
            cache: 'npm'
        - run: npm ci
        - run: npm run test:coverage
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js lts
          uses: actions/setup-node@v3
          with:
            node-version: 'lts/*'
            cache: 'npm'
        - run: npm ci
        - run: npm run lint
    build:
      needs: [ test, lint]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js lts
          uses: actions/setup-node@v3
          with:
            node-version: 'lts/*'
            cache: 'npm'
        - run: npm ci
        - run: npm run build
